// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.28.3
// source: pedido.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServicoPedidosClient is the client API for ServicoPedidos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicoPedidosClient interface {
	ListarPedidos(ctx context.Context, in *RequisicaoListarPedidos, opts ...grpc.CallOption) (*RespostaListarPedidos, error)
}

type servicoPedidosClient struct {
	cc grpc.ClientConnInterface
}

func NewServicoPedidosClient(cc grpc.ClientConnInterface) ServicoPedidosClient {
	return &servicoPedidosClient{cc}
}

func (c *servicoPedidosClient) ListarPedidos(ctx context.Context, in *RequisicaoListarPedidos, opts ...grpc.CallOption) (*RespostaListarPedidos, error) {
	out := new(RespostaListarPedidos)
	err := c.cc.Invoke(ctx, "/pb.ServicoPedidos/ListarPedidos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicoPedidosServer is the server API for ServicoPedidos service.
// All implementations must embed UnimplementedServicoPedidosServer
// for forward compatibility
type ServicoPedidosServer interface {
	ListarPedidos(context.Context, *RequisicaoListarPedidos) (*RespostaListarPedidos, error)
	mustEmbedUnimplementedServicoPedidosServer()
}

// UnimplementedServicoPedidosServer must be embedded to have forward compatible implementations.
type UnimplementedServicoPedidosServer struct {
}

func (UnimplementedServicoPedidosServer) ListarPedidos(context.Context, *RequisicaoListarPedidos) (*RespostaListarPedidos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListarPedidos not implemented")
}
func (UnimplementedServicoPedidosServer) mustEmbedUnimplementedServicoPedidosServer() {}

// UnsafeServicoPedidosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicoPedidosServer will
// result in compilation errors.
type UnsafeServicoPedidosServer interface {
	mustEmbedUnimplementedServicoPedidosServer()
}

func RegisterServicoPedidosServer(s grpc.ServiceRegistrar, srv ServicoPedidosServer) {
	s.RegisterService(&ServicoPedidos_ServiceDesc, srv)
}

func _ServicoPedidos_ListarPedidos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequisicaoListarPedidos)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicoPedidosServer).ListarPedidos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ServicoPedidos/ListarPedidos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicoPedidosServer).ListarPedidos(ctx, req.(*RequisicaoListarPedidos))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicoPedidos_ServiceDesc is the grpc.ServiceDesc for ServicoPedidos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicoPedidos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ServicoPedidos",
	HandlerType: (*ServicoPedidosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListarPedidos",
			Handler:    _ServicoPedidos_ListarPedidos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pedido.proto",
}
