// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.3
// source: pedido.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequisicaoListarPedidos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequisicaoListarPedidos) Reset() {
	*x = RequisicaoListarPedidos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedido_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequisicaoListarPedidos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequisicaoListarPedidos) ProtoMessage() {}

func (x *RequisicaoListarPedidos) ProtoReflect() protoreflect.Message {
	mi := &file_pedido_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequisicaoListarPedidos.ProtoReflect.Descriptor instead.
func (*RequisicaoListarPedidos) Descriptor() ([]byte, []int) {
	return file_pedido_proto_rawDescGZIP(), []int{0}
}

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdCliente    string  `protobuf:"bytes,2,opt,name=id_cliente,json=idCliente,proto3" json:"id_cliente,omitempty"`
	Status       string  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ValorTotal   float64 `protobuf:"fixed64,4,opt,name=valor_total,json=valorTotal,proto3" json:"valor_total,omitempty"`
	CriadoEm     string  `protobuf:"bytes,5,opt,name=criado_em,json=criadoEm,proto3" json:"criado_em,omitempty"`
	AtualizadoEm string  `protobuf:"bytes,6,opt,name=atualizado_em,json=atualizadoEm,proto3" json:"atualizado_em,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedido_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_pedido_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_pedido_proto_rawDescGZIP(), []int{1}
}

func (x *Pedido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pedido) GetIdCliente() string {
	if x != nil {
		return x.IdCliente
	}
	return ""
}

func (x *Pedido) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pedido) GetValorTotal() float64 {
	if x != nil {
		return x.ValorTotal
	}
	return 0
}

func (x *Pedido) GetCriadoEm() string {
	if x != nil {
		return x.CriadoEm
	}
	return ""
}

func (x *Pedido) GetAtualizadoEm() string {
	if x != nil {
		return x.AtualizadoEm
	}
	return ""
}

type RespostaListarPedidos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pedidos []*Pedido `protobuf:"bytes,1,rep,name=pedidos,proto3" json:"pedidos,omitempty"`
}

func (x *RespostaListarPedidos) Reset() {
	*x = RespostaListarPedidos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedido_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespostaListarPedidos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespostaListarPedidos) ProtoMessage() {}

func (x *RespostaListarPedidos) ProtoReflect() protoreflect.Message {
	mi := &file_pedido_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespostaListarPedidos.ProtoReflect.Descriptor instead.
func (*RespostaListarPedidos) Descriptor() ([]byte, []int) {
	return file_pedido_proto_rawDescGZIP(), []int{2}
}

func (x *RespostaListarPedidos) GetPedidos() []*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

var File_pedido_proto protoreflect.FileDescriptor

var file_pedido_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x19, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x75, 0x69, 0x73, 0x69, 0x63, 0x61, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x22, 0xb2, 0x01,
	0x0a, 0x06, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x64, 0x5f, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x64,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x72, 0x69, 0x61, 0x64, 0x6f, 0x5f, 0x65, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x72, 0x69, 0x61, 0x64, 0x6f, 0x45, 0x6d, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f, 0x5f, 0x65, 0x6d, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x6f,
	0x45, 0x6d, 0x22, 0x3d, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x12, 0x24, 0x0a, 0x07, 0x70,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f,
	0x73, 0x32, 0x5b, 0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x6f, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x73, 0x12, 0x49, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x69, 0x73,
	0x69, 0x63, 0x61, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f,
	0x73, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x4c,
	0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x22, 0x00, 0x42, 0x38,
	0x5a, 0x36, 0x67, 0x69, 0x74, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x77, 0x61, 0x6e, 0x64,
	0x65, 0x72, 0x6c, 0x65, 0x69, 0x32, 0x35, 0x38, 0x33, 0x2f, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x5f,
	0x61, 0x72, 0x71, 0x75, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pedido_proto_rawDescOnce sync.Once
	file_pedido_proto_rawDescData = file_pedido_proto_rawDesc
)

func file_pedido_proto_rawDescGZIP() []byte {
	file_pedido_proto_rawDescOnce.Do(func() {
		file_pedido_proto_rawDescData = protoimpl.X.CompressGZIP(file_pedido_proto_rawDescData)
	})
	return file_pedido_proto_rawDescData
}

var file_pedido_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pedido_proto_goTypes = []interface{}{
	(*RequisicaoListarPedidos)(nil), // 0: pb.RequisicaoListarPedidos
	(*Pedido)(nil),                  // 1: pb.Pedido
	(*RespostaListarPedidos)(nil),   // 2: pb.RespostaListarPedidos
}
var file_pedido_proto_depIdxs = []int32{
	1, // 0: pb.RespostaListarPedidos.pedidos:type_name -> pb.Pedido
	0, // 1: pb.ServicoPedidos.ListarPedidos:input_type -> pb.RequisicaoListarPedidos
	2, // 2: pb.ServicoPedidos.ListarPedidos:output_type -> pb.RespostaListarPedidos
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pedido_proto_init() }
func file_pedido_proto_init() {
	if File_pedido_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pedido_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequisicaoListarPedidos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pedido_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pedido_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespostaListarPedidos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pedido_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pedido_proto_goTypes,
		DependencyIndexes: file_pedido_proto_depIdxs,
		MessageInfos:      file_pedido_proto_msgTypes,
	}.Build()
	File_pedido_proto = out.File
	file_pedido_proto_rawDesc = nil
	file_pedido_proto_goTypes = nil
	file_pedido_proto_depIdxs = nil
}
